name: CI

on:
  push:
    branches:
      -main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        whit:
          python-version: '3.8'

      - name: Venv Environments
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Run tests
        run: |
          source venv/bin/activate
          python -m unittest test/test_main.py